# Generated by Django 3.0.1 on 2019-12-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('left_side_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('right_side_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('back_side_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_sub.SubCategory')),
            ],
        ),
    ]
