# Generated by Django 3.0.1 on 2019-12-27 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_cart_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('refunded', 'Refunded'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='created', max_length=120)),
                ('shipping_total', models.FloatField(default=45.0, max_length=120)),
                ('total', models.FloatField(default=0, max_length=120)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
