# Generated by Django 3.0.1 on 2019-12-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191225_1416'),
        ('mobiles', '0002_auto_20191225_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='name',
            field=models.CharField(default='abc', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
