# Generated by Django 3.0.1 on 2019-12-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_auto_20191225_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(default='abc', max_length=120),
        ),
    ]
