# Generated by Django 3.0.1 on 2019-12-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_mobile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
