# Generated by Django 3.0.1 on 2019-12-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_auto_20191225_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='ram',
            field=models.FloatField(blank=True, default=1.0, max_length=120, null=True),
        ),
    ]
