# Generated by Django 3.0.1 on 2019-12-25 14:26

from django.db import migrations, models
import product_details.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0008_mobile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='back_side_image',
            field=models.ImageField(blank=True, null=True, upload_to=product_details.utils.upload_image_path),
        ),
        migrations.AddField(
            model_name='mobile',
            name='left_side_image',
            field=models.ImageField(blank=True, null=True, upload_to=product_details.utils.upload_image_path),
        ),
        migrations.AddField(
            model_name='mobile',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=product_details.utils.upload_image_path),
        ),
        migrations.AddField(
            model_name='mobile',
            name='right_side_image',
            field=models.ImageField(blank=True, null=True, upload_to=product_details.utils.upload_image_path),
        ),
    ]
