# Generated by Django 3.0.1 on 2019-12-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0009_auto_20191225_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
