# Generated by Django 3.0.1 on 2019-12-27 05:38

import cart.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tax',
            field=models.FloatField(default=1.0, max_length=120, validators=[cart.utils.validate_tax]),
        ),
    ]
