# Generated by Django 3.0.1 on 2019-12-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_auto_20191225_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
